services:
  db:
    image: postgres:17
    container_name: audit_db
    environment:
      POSTGRES_USER: audit
      POSTGRES_PASSWORD: auditpw
      POSTGRES_DB: auditdb
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db.sql:/docker-entrypoint-initdb.d/00_db.sql

  minio:
    image: minio/minio
    container_name: audit_minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports: ["9000:9000","9001:9001"]
    volumes:
      - minio:/data

volumes:
  pgdata:
  minio:
